apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1  #Number of container running-up
  selector: # Pod select label
    matchLabels:
      app: mysql
  strategy: #Strategy for our deployment, and behavior
    type: Recreate
  template: # Pod template
    metadata:
      labels:
        app: mysql
    spec: #Pod Specification
      containers:
        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: dbpassword11
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: usermanagement-dbcreation
              mountPath: /docker-entrypoint-initdb.d
      volumes: #Pod Specification level resource
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: azure-managed-disk-pvc
        - name: usermanagement-dbcreation
          configMap:
            name: usermanagement-dbcreation
