apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-partition-volume-claim
spec:
  acceesModes:
  - ReadWriteOnce
  storageClassName: managed-premium-retain-sc
  resources:
    requests:
      storage: 5Gi


#PVC => Partition VOlume Claim