apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-retain-sc
provisioner: kubernet.io/azure-disk  #TOOO important
parameters:
  storageAccountType: Premium_LRS
  kind: managed
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer  #Important
reclaimPolicy: Retain #Important

##
#What is volumeBindingMode ??
#What is reclaimPolicy ??

