apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-retain-sc
provisioner: kubernetes.io/azure-disk  #TOOO important
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer  #Important
reclaimPolicy: Retain #Important
parameters:
  storageAccountType: Premium_LRS
  kind: Managed
##
#What is volumeBindingMode ??
#What is reclaimPolicy ??