apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-restapp
  labels:
    app: backend-restapp
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-restapp
    template:
      metadata:
        labels:
          app: backend-restapp
          tier: backend
      spec:
        containers:
          - name: backend-restapp
            image: stacksimplify/kube-helloword:1.0.0
            ports:
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-backend-service ## This is REALLY improtant for NGINX!!
spec:
  type: ClusterIP
  selector:
    app: backend-restapp
  ports:
    - name : http
      port: 8080
      targetPort: 8080