apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  labels:
    app: web-app-test
  namespace: default
spec:
  containers:
    - name: web-app-test
      image: stacksimplify/kubenginx:1.0.0
      ports:
        - containerPort: 80 
 #     command: ['']
 #     args: ['Hello world']
---
apiVersion: v1
kind: Service
metadata:
  name: pod-example-loadbalancer-service
spec:
  type: LoadBalancer # Clound be ClusterIP, NoderPort... so on
  selector: 
    app: web-app-test
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rset-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app-test-rs
  template:   #Pod templates
    metadata:
      name: pod-example
      labels:
        app: web-app-test-rs
      namespace: default
    spec:
      containers:
        - name: web-app-test-rs
          image: stacksimplify/kubenginx:2.0.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: replicaset-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: web-app-test-rs
  ports:
    - name: http
      port: 80
      targetPort: 80


#Type of kubernet object
# POD ---
# ReplicaSet ---
# Deployment ---
# Service --- 
# and more.... (this will explain later)

#ApiVersion --> This is the version of k8s object 
#kind: ---> type of k8s object (pod, replicaset....)
#metadata: --> Define name and labels for k8s object
#spec:  --> specification or real difinition for k8s object
